"""Build the free-tier QuantConnect Python module for the Q-LIR calendar."""

from __future__ import annotations

from base64 import b64encode
from hashlib import sha256
from pathlib import Path
from textwrap import wrap
from zlib import compress

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "calendars" / "macro_events_v2.csv"
OUTPUT = ROOT / "qc" / "macro_events_v2_embedded.py"


def main() -> None:
    # Canonical LF bytes make the payload identical on Windows and Linux.
    source = SOURCE.read_bytes().replace(b"\r\n", b"\n")
    payload = b64encode(compress(source, level=9)).decode("ascii")
    payload_lines = "\n".join(f'    "{line}"' for line in wrap(payload, 88))
    digest = sha256(source).hexdigest()
    module = f'''"""Generated Q-LIR macro calendar for free-tier QC Research.

Do not edit this file by hand. Rebuild it with scripts/embed_macro_calendar.py.
"""

from base64 import b64decode
from zlib import decompress

MACRO_CALENDAR_SHA256 = "{digest}"

_PAYLOAD = (
{payload_lines}
)


def macro_calendar_csv_text():
    """Return the frozen calendar as UTF-8 CSV text."""
    return decompress(b64decode(_PAYLOAD)).decode("utf-8")
'''
    OUTPUT.write_text(module, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT} (source sha256={digest})")


if __name__ == "__main__":
    main()
