"""C003: marginal-value-theorem patch-abandonment reversal."""

SIGNAL_KIND = "episode_reversal"
ORIGIN = "G3"
HOLDOUT_END = "2030-01-01"
EPISODE_Z = 2.0
LOOKBACK = 10
HOLD = 10
QUANTILE = 0.5
MIN_NAMES = 4
VOL_WINDOW = 63
RETURN_WINDOW = 1
BREADTH_THRESHOLD = 20
BROAD_TAIL = 0.1
THIN_TAIL = 0.3333333333333333
PERTURBATIONS = (
    "EPISODE_Z",
    "LOOKBACK",
    "VOL_WINDOW",
    "RETURN_WINDOW",
    "BREADTH_THRESHOLD",
    "BROAD_TAIL",
    "THIN_TAIL",
    "HOLD",
    "QUANTILE",
    "MIN_NAMES",
)
